name = "Black Ember"
background = "#171614"
surface = "#35312c"
overlay = "#625a50"
foreground = "#e8dfd0"
muted = "#a69a8b"
accent = "#bd8857"
accent_secondary = "#e2a35f"
success = "#9caa76"
warning = "#e7bd72"
error = "#bd5548"
teal = "#8da39a"
peach = "#e2a35f"
color0 = "#171614"
color1 = "#bd5548"
color2 = "#9caa76"
color3 = "#e7bd72"
color4 = "#8b8176"
color5 = "#bd8857"
color6 = "#8da39a"
color7 = "#e8dfd0"
color8 = "#625a50"
color9 = "#d86453"
color10 = "#b4c285"
color11 = "#f0ca7a"
color12 = "#aaa094"
color13 = "#d3a16e"
color14 = "#9eb6ac"
color15 = "#fff7eb"
